#!/usr/bin/env bash
# Core helpers - sourced by all other libs

# Logging
section() { echo -e "\n==> $*"; }
log()     { echo "    $*"; }
warn()    { echo "WARN: $*" >&2; }
die()     { echo "ERROR: $*" >&2; exit 1; }

# Idempotency
has()       { command -v "$1" &>/dev/null; }
installed() { dpkg -l "$1" 2>/dev/null | grep -q "^ii"; }

# Sudo handling with keep-alive for long operations
need_sudo() {
    log "Requesting sudo (may prompt for password)..."
    sudo -v || die "sudo required"
    # Keep sudo alive in background for long operations (tmux build, etc.)
    (while true; do sudo -v; sleep 50; done) &
    SUDO_KEEPALIVE_PID=$!
    trap "kill $SUDO_KEEPALIVE_PID 2>/dev/null" EXIT
}

# Package installation
install_apt() {
    local to_install=()
    for pkg in "$@"; do
        installed "$pkg" || to_install+=("$pkg")
    done
    [[ ${#to_install[@]} -eq 0 ]] && return 0
    log "Installing: ${to_install[*]}"
    sudo apt-get update -qq
    sudo apt-get install -y "${to_install[@]}" || die "apt-get install failed"
}

install_cargo() {
    has cargo-binstall || die "cargo-binstall not found - run install_rust first"
    for tool in "$@"; do
        if ! has "$tool"; then
            log "Installing $tool via cargo-binstall..."
            "$HOME/.cargo/bin/cargo-binstall" -y "$tool" \
                || die "cargo-binstall $tool failed"
        fi
    done
}

# Config management - validates symlink points to correct source
link_config() {
    local src="$1" dest="$2"

    # Check if already correctly linked
    if [[ -L "$dest" ]]; then
        if [[ "$(readlink "$dest")" == "$src" ]]; then
            log "Already linked: $dest"
            return 0
        else
            log "Updating symlink: $dest (was pointing to $(readlink "$dest"))"
            rm "$dest"
        fi
    fi

    # Backup existing file
    if [[ -e "$dest" ]]; then
        log "Backing up: $dest"
        mv "$dest" "$dest.bak.$(date +%s)"
    fi

    # Create parent directory if needed
    mkdir -p "$(dirname "$dest")"

    log "Linking: $dest -> $src"
    ln -s "$src" "$dest"
}

clone_or_pull() {
    local repo="$1" dest="$2"
    export GIT_TERMINAL_PROMPT=0  # Fail fast instead of prompting for creds

    if [[ -d "$dest" ]]; then
        log "Updating: $dest"
        git -C "$dest" pull --quiet || warn "git pull failed for $dest (continuing)"
    else
        log "Cloning: $repo"
        git clone --depth 1 --quiet "$repo" "$dest" \
            || die "git clone failed for $repo"
    fi
}

# Download with error checking
download() {
    local url="$1" dest="$2"
    log "Downloading: $url"
    curl -fsSL "$url" -o "$dest" || die "Download failed: $url"
}

# PDE config directory
create_pde_config() {
    mkdir -p "$HOME/.config/pde"
    cat > "$HOME/.config/pde/paths.env" <<EOF
# Personal Dev Environment configuration
# Auto-generated by pde installer
export PDE_INSTALL_PATH="$SCRIPT_DIR"
export PDE_PROFILE="${PDE_PROFILE:-unknown}"
EOF
    log "Created ~/.config/pde/paths.env"
}
