package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type configLink struct {
	src string
	dst string
}

var managedSharedConfigLinks = []configLink{
	{src: filepath.Join("pde", "config", "zsh", "zshrc"), dst: ".zshrc"},
	{src: filepath.Join("pde", "config", "zsh", "zsh_plugins.txt"), dst: ".zsh_plugins.txt"},
	{src: filepath.Join("pde", "config", "tmux", "tmux.conf"), dst: ".tmux.conf"},
	{src: filepath.Join("pde", "config", "p10k", "p10k.zsh"), dst: ".p10k.zsh"},
	{src: filepath.Join("pde", "config", "bottom", "bottom.toml"), dst: filepath.Join(".config", "bottom", "bottom.toml")},
}

func installConfig(cfg *Config, runner Runner) error {
	if err := writePDEPathsEnv(cfg, runner); err != nil {
		return err
	}

	for _, link := range managedSharedConfigLinks {
		if err := linkConfig(filepath.Join(cfg.RepoRoot, link.src), filepath.Join(cfg.HomeDir, link.dst), runner); err != nil {
			return err
		}
	}

	return nil
}

func writePDEPathsEnv(cfg *Config, runner Runner) error {
	pathsEnv := filepath.Join(cfg.PDEConfigDir, "paths.env")
	profileLine, err := readExistingPDEProfileLine(pathsEnv)
	if err != nil {
		return err
	}
	if profileLine == "" {
		// The minimal profile is the baseline shared setup.
		profileLine = `export PDE_PROFILE="minimal"`
	}

	content := strings.Join([]string{
		"# Personal Dev Environment configuration",
		"# Auto-generated by pde installer",
		fmt.Sprintf("export PDE_INSTALL_PATH=%q", cfg.RepoRoot),
		profileLine,
		"",
	}, "\n")

	if err := runner.MkdirAll("create PDE config dir", cfg.PDEConfigDir, 0o755); err != nil {
		return err
	}
	return runner.WriteFile("write PDE paths.env", pathsEnv, []byte(content), 0o644)
}

func readExistingPDEProfileLine(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(strings.TrimSpace(line), "export PDE_PROFILE=") {
			return line, nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", err
	}
	return "", nil
}
