
func validateAIConfigSource(path string)error{i,err:=os.Lstat(path);if err!=nil{return fmt.Errorf("validate AI config source %s: %w",path,err)};if i.Mode().IsRegular(){return validateReadableRegularFile(path)};if !i.IsDir(){return fmt.Errorf("AI config source is not a file or directory: %s",path)};return filepath.WalkDir(path,func(p string,e fs.DirEntry,w error)error{if w!=nil{return w};info,err:=e.Info();if err!=nil{return err};if info.IsDir()||info.Mode()&os.ModeSymlink!=0{return nil};if !info.Mode().IsRegular(){return fmt.Errorf("unsupported AI config source: %s",p)};return validateReadableRegularFile(p)})}
func validateSkillCollision(c aiConfigChange,owned bool,ignored map[string]struct{})error{exists,err:=pathExists(c.destination);if err!=nil||!exists||owned{return err};equal,err:=equalTrees(c.source,c.destination,ignored);if err!=nil{return err};if !equal{return fmt.Errorf("unmanaged skill collision at %s",c.destination)};return nil}
func equalTrees(left,right string,ignored map[string]struct{})(bool,error){a,err:=snapshotTree(left,ignored);if err!=nil{return false,err};b,err:=snapshotTree(right,ignored);if err!=nil{return false,err};if len(a)!=len(b){return false,nil};for p,x:=range a{y,ok:=b[p];if !ok||x.mode!=y.mode||x.target!=y.target||!bytes.Equal(x.data,y.data){return false,nil}};return true,nil}
func snapshotTree(root string,ignored map[string]struct{})(map[string]treeEntry,error){out:=map[string]treeEntry{};err:=filepath.WalkDir(root,func(p string,e fs.DirEntry,w error)error{if w!=nil{return w};rel,err:=filepath.Rel(root,p);if err!=nil||rel=="."{return err};if _,ok:=ignored[filepath.ToSlash(rel)];ok{if e.IsDir(){return filepath.SkipDir};return nil};i,err:=e.Info();if err!=nil{return err};x:=treeEntry{mode:i.Mode()};if i.Mode()&os.ModeSymlink!=0{x.target,err=os.Readlink(p)}else if i.Mode().IsRegular(){x.data,err=os.ReadFile(p)};if err!=nil{return err};out[rel]=x;return nil});return out,err}
func copyAIConfigSource(source,destination string)error{i,err:=os.Stat(source);if err!=nil{return err};if i.IsDir(){return copyTreeInto(source,destination)};data,err:=os.ReadFile(source);if err!=nil{return err};if err:=os.MkdirAll(filepath.Dir(destination),0755);err!=nil{return err};return os.WriteFile(destination,data,i.Mode().Perm())}
func pathExists(path string)(bool,error){_,err:=os.Lstat(path);if os.IsNotExist(err){return false,nil};return err==nil,err}
func nameSet(names []string)map[string]bool{s:=make(map[string]bool,len(names));for _,n:=range names{s[n]=true};return s}
func intersectNames(left,right []string)[]string{r:=nameSet(right);var out []string;for _,n:=range left{if r[n]{out=append(out,n)}};return out}

func legacyAgentSkillBackupChanges(cfg *Config)([]aiConfigChange,error){root:=filepath.Join(cfg.HomeDir,".agents","skills");entries,err:=os.ReadDir(root);if os.IsNotExist(err){return nil,nil};if err!=nil{return nil,fmt.Errorf("read legacy skill backups: %w",err)};const prefix="git-messages.backup.";var out []aiConfigChange;for _,e:=range entries{if !strings.HasPrefix(e.Name(),prefix){continue};if !e.IsDir(){return nil,fmt.Errorf("legacy skill backup is not a directory: %s",e.Name())};if _,err:=time.Parse("20060102_150405",strings.TrimPrefix(e.Name(),prefix));err!=nil{return nil,fmt.Errorf("invalid legacy skill backup name: %s",e.Name())};dest:=filepath.Join(root,e.Name());n,err:=readSkillFrontmatterName(filepath.Join(dest,"SKILL.md"));if err!=nil{return nil,err};if n!="git-messages"{return nil,fmt.Errorf("legacy skill backup has unexpected name %q: %s",n,dest)};out=append(out,newAIConfigChange("",dest,filepath.Join("legacy-agents-skills",e.Name())))};return out,nil}
