package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type configLink struct {
	src string
	dst string
}

func managedSharedConfigLinks(cfg *Config) []configLink {
	return []configLink{
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "zsh", "zshrc"), dst: filepath.Join(cfg.HomeDir, ".zshrc")},
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "zsh", "zsh_plugins.txt"), dst: filepath.Join(cfg.HomeDir, ".zsh_plugins.txt")},
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "tmux", "tmux.conf"), dst: filepath.Join(cfg.HomeDir, ".tmux.conf")},
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "p10k", "p10k.zsh"), dst: filepath.Join(cfg.HomeDir, ".p10k.zsh")},
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "bottom", "bottom.toml"), dst: filepath.Join(cfg.HomeDir, ".config", "bottom", "bottom.toml")},
	}
}

func installConfig(cfg *Config, runner Runner) error {
	links := managedSharedConfigLinks(cfg)
	if err := preflightManagedSharedConfigSources(links); err != nil {
		return err
	}

	profileLine, err := existingPDEProfileLine(filepath.Join(cfg.PDEConfigDir, "paths.env"))
	if err != nil {
		return err
	}

	if err := writePDEPathsEnv(cfg, profileLine, runner); err != nil {
		return err
	}

	for _, link := range links {
		if err := linkConfig(link.src, link.dst, runner); err != nil {
			return err
		}
	}

	return nil
}

func preflightManagedSharedConfigSources(links []configLink) error {
	for _, link := range links {
		if err := validateReadableRegularFile(link.src); err != nil {
			return fmt.Errorf("validate managed source %s: %w", link.src, err)
		}
	}
	return nil
}

func writePDEPathsEnv(cfg *Config, profileLine string, runner Runner) error {
	pathsEnv := filepath.Join(cfg.PDEConfigDir, "paths.env")
	lines := []string{
		"# Personal Dev Environment configuration",
		"# Auto-generated by pde installer",
		fmt.Sprintf("export PDE_INSTALL_PATH=%q", cfg.RepoRoot),
	}
	if profileLine != "" {
		lines = append(lines, profileLine)
	}
	lines = append(lines, "")

	content := strings.Join(lines, "\n")

	if err := backupConfigInstallPath(pathsEnv, runner); err != nil {
		return err
	}
	if err := runner.MkdirAll("create PDE config dir", cfg.PDEConfigDir, 0o755); err != nil {
		return err
	}
	return runner.WriteFile("write PDE paths.env", pathsEnv, []byte(content), 0o644)
}

func existingPDEProfileLine(path string) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return "", nil
	}
	if !info.Mode().IsRegular() {
		return "", nil
	}

	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("open existing PDE profile file %s: %w", path, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(strings.TrimSpace(line), "export PDE_PROFILE=") {
			return line, nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scan existing PDE profile file %s: %w", path, err)
	}
	return "", nil
}
