package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type configLink struct {
	src string
	dst string
}

func managedSharedConfigLinks(cfg *Config) []configLink {
	return []configLink{
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "zsh", "zshrc"), dst: filepath.Join(cfg.HomeDir, ".zshrc")},
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "zsh", "zsh_plugins.txt"), dst: filepath.Join(cfg.HomeDir, ".zsh_plugins.txt")},
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "tmux", "tmux.conf"), dst: filepath.Join(cfg.HomeDir, ".tmux.conf")},
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "p10k", "p10k.zsh"), dst: filepath.Join(cfg.HomeDir, ".p10k.zsh")},
		{src: filepath.Join(cfg.RepoRoot, "pde", "config", "bottom", "bottom.toml"), dst: filepath.Join(cfg.HomeDir, ".config", "bottom", "bottom.toml")},
	}
}

func installConfig(cfg *Config, runner Runner) error {
	links := managedSharedConfigLinks(cfg)
	if err := preflightManagedSharedConfigSources(links); err != nil {
		return err
	}

	existingLines, err := existingPDEPathsEnvLines(filepath.Join(cfg.PDEConfigDir, "paths.env"))
	if err != nil {
		return err
	}

	if err := writePDEPathsEnv(cfg, existingLines, runner); err != nil {
		return err
	}

	for _, link := range links {
		if err := linkConfig(link.src, link.dst, runner); err != nil {
			return err
		}
	}

	return nil
}

func preflightManagedSharedConfigSources(links []configLink) error {
	for _, link := range links {
		if err := validateReadableRegularFile(link.src); err != nil {
			return fmt.Errorf("validate managed source %s: %w", link.src, err)
		}
	}
	return nil
}

func writePDEPathsEnv(cfg *Config, existingLines map[string]string, runner Runner) error {
	pathsEnv := filepath.Join(cfg.PDEConfigDir, "paths.env")
	lines := []string{
		"# Personal Dev Environment configuration",
		"# Auto-generated by pde installer",
		fmt.Sprintf("export PDE_INSTALL_PATH=%q", cfg.RepoRoot),
	}
	for _, key := range []string{"PDE_PROFILE", "PDE_MAIN_VAULT", "PDE_WORK_VAULT"} {
		if line, ok := existingLines[key]; ok {
			lines = append(lines, line)
		}
	}
	lines = append(lines, "")

	content := strings.Join(lines, "\n")

	if err := backupConfigInstallPath(pathsEnv, runner); err != nil {
		return err
	}
	if err := runner.MkdirAll("create PDE config dir", cfg.PDEConfigDir, 0o755); err != nil {
		return err
	}
	return runner.WriteFile("write PDE paths.env", pathsEnv, []byte(content), 0o644)
}

func existingPDEPathsEnvLines(path string) (map[string]string, error) {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]string{}, nil
		}
		return nil, fmt.Errorf("stat existing PDE paths.env file %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return map[string]string{}, nil
	}

	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open existing PDE paths.env file %s: %w", path, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lines := map[string]string{}
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		for _, key := range []string{"PDE_PROFILE", "PDE_MAIN_VAULT", "PDE_WORK_VAULT"} {
			if strings.HasPrefix(trimmed, "export "+key+"=") {
				if _, ok := lines[key]; !ok {
					lines[key] = line
				}
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan existing PDE paths.env file %s: %w", path, err)
	}
	return lines, nil
}
