package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestReadConfig(t *testing.T) {
	tests := []struct {
		name    string
		seed    string
		want    VaultState
		wantErr bool
	}{
		{name: "missingcfg", want: VaultState{}},
		{
			name: "existingcfg",
			seed: "export PDE_MAIN_VAULT=\"/vaults/main\"\nexport PDE_WORK_VAULT=\"/vaults/work\"\nexport PDE_DEFAULT_VAULT=\"main\"\n",
			want: VaultState{MainPath: "/vaults/main", WorkPath: "/vaults/work", Default: "main"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			homeDir := t.TempDir()
			pathsEnv := filepath.Join(homeDir, ".config", "pde", "paths.env")
			if tt.seed != "" {
				if err := os.MkdirAll(filepath.Dir(pathsEnv), 0o755); err != nil {
					t.Fatalf("mkdir paths.env parent: %v", err)
				}
				mustWriteFile(t, pathsEnv, tt.seed, 0o644)
			}

			got, err := readVaultState(homeDir)
			if (err != nil) != tt.wantErr {
				t.Fatalf("read vault state error = %v wantErr %v", err, tt.wantErr)
			}
			if got != tt.want {
				t.Fatalf("read vault state = %#v want %#v", got, tt.want)
			}
		})
	}
}

func TestWriteConfig(t *testing.T) {
	tests := []struct {
		name       string
		seed       string
		state      VaultState
		want       string
		wantCounts map[string]int
	}{
		{
			name:  "missingcfg",
			state: VaultState{MainPath: "/vaults/main", WorkPath: "/vaults/work", Default: "main"},
			want: "# Personal Dev Environment configuration\n# Auto-generated by pde installer\n\nexport PDE_MAIN_VAULT=\"/vaults/main\"\n\nexport PDE_WORK_VAULT=\"/vaults/work\"\n\nexport PDE_DEFAULT_VAULT=\"main\"\n",
			wantCounts: map[string]int{
				"export PDE_MAIN_VAULT=":    1,
				"export PDE_WORK_VAULT=":    1,
				"export PDE_DEFAULT_VAULT=": 1,
			},
		},
		{
			name:  "existingcfg",
			seed:  "# existing\nexport OPENCODE_BASE_URL=\"http://127.0.0.1:4199\"\n",
			state: VaultState{MainPath: "/vaults/main", WorkPath: "/vaults/work", Default: "work"},
			want: "# existing\nexport OPENCODE_BASE_URL=\"http://127.0.0.1:4199\"\n\nexport PDE_MAIN_VAULT=\"/vaults/main\"\n\nexport PDE_WORK_VAULT=\"/vaults/work\"\n\nexport PDE_DEFAULT_VAULT=\"work\"\n",
			wantCounts: map[string]int{
				"export PDE_MAIN_VAULT=":    1,
				"export PDE_WORK_VAULT=":    1,
				"export PDE_DEFAULT_VAULT=": 1,
				"export OPENCODE_BASE_URL=": 1,
			},
		},
		{
			name:  "dedupeexistingcfg",
			seed:  "export PDE_MAIN_VAULT=\"/old/main\"\nexport PDE_MAIN_VAULT=\"/older/main\"\nexport PDE_WORK_VAULT=\"/old/work\"\nexport PDE_DEFAULT_VAULT=\"old\"\nexport KEEP=\"1\"\n",
			state: VaultState{MainPath: "/vaults/main", WorkPath: "/vaults/work", Default: "work"},
			want: "export PDE_MAIN_VAULT=\"/vaults/main\"\nexport PDE_WORK_VAULT=\"/vaults/work\"\nexport PDE_DEFAULT_VAULT=\"work\"\nexport KEEP=\"1\"\n",
			wantCounts: map[string]int{
				"export PDE_MAIN_VAULT=":    1,
				"export PDE_WORK_VAULT=":    1,
				"export PDE_DEFAULT_VAULT=": 1,
				"export KEEP=":             1,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			homeDir := t.TempDir()
			pathsEnv := filepath.Join(homeDir, ".config", "pde", "paths.env")
			if tt.seed != "" {
				if err := os.MkdirAll(filepath.Dir(pathsEnv), 0o755); err != nil {
					t.Fatalf("mkdir paths.env parent: %v", err)
				}
				mustWriteFile(t, pathsEnv, tt.seed, 0o644)
			}

			if err := writeVaultState(homeDir, tt.state); err != nil {
				t.Fatalf("write vault state: %v", err)
			}

			content := mustFileContents(t, pathsEnv, tt.want)
			for prefix, wantCount := range tt.wantCounts {
				if got := strings.Count(content, prefix); got != wantCount {
					t.Fatalf("count for %q = %d want %d\n%s", prefix, got, wantCount, content)
				}
			}
		})
	}
}
