package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const defaultVaultEnvKey = "PDE_DEFAULT_VAULT"

type VaultState struct {
	MainPath string
	WorkPath string
	Default  string
}

func readVaultState(homeDir string) (VaultState, error) {
	path := filepath.Join(homeDir, ".config", "pde", "paths.env")
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return VaultState{}, nil
		}
		return VaultState{}, newVaultError(vaultReadConfigFailed, err, err)
	}
	defer f.Close()

	state := VaultState{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "export ") {
			continue
		}
		key, value, ok := strings.Cut(strings.TrimPrefix(line, "export "), "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		if len(value) >= 2 && ((value[0] == '"' && value[len(value)-1] == '"') || (value[0] == '\'' && value[len(value)-1] == '\'')) {
			value = value[1 : len(value)-1]
		}

		switch key {
		case "PDE_MAIN_VAULT":
			state.MainPath = value
		case "PDE_WORK_VAULT":
			state.WorkPath = value
		case defaultVaultEnvKey:
			state.Default = value
		}
	}
	if err := scanner.Err(); err != nil {
		return VaultState{}, newVaultError(vaultReadConfigFailed, err, err)
	}

	return state, nil
}

func writeVaultState(homeDir string, state VaultState) error {
	if state.Default != "" && state.Default != "main" && state.Default != "work" {
		return newVaultError(vaultInvalidSelector, nil, state.Default)
	}

	path := filepath.Join(homeDir, ".config", "pde", "paths.env")
	content := ""
	info, err := os.Stat(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return newVaultError(vaultReadConfigFailed, err, err)
		}
	} else if info.Mode().IsRegular() {
		data, err := os.ReadFile(path)
		if err != nil {
			return newVaultError(vaultReadConfigFailed, err, err)
		}
		content = string(data)
	}

	if content == "" {
		content = strings.Join([]string{
			"# Personal Dev Environment configuration",
			"# Auto-generated by pde installer",
			"",
		}, "\n")
	}

	content = writeHelper(content, state)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return newVaultError(vaultWriteConfigFailed, err, err)
	}
	if err := backupConfigInstallPath(path, Runner{}); err != nil {
		return newVaultError(vaultWriteConfigFailed, err, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return newVaultError(vaultWriteConfigFailed, err, err)
	}
	return nil
}

func writeHelper(content string, state VaultState) string {
	content = strings.ReplaceAll(content, "\r\n", "\n")

	for _, item := range []struct {
		key   string
		value string
	}{
		{key: "PDE_MAIN_VAULT", value: state.MainPath},
		{key: "PDE_WORK_VAULT", value: state.WorkPath},
		{key: defaultVaultEnvKey, value: state.Default},
	} {
		lines := strings.Split(content, "\n")
		prefix := "export " + item.key + "="
		updated := make([]string, 0, len(lines)+1)
		replaced := false
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, prefix) {
				if replaced {
					continue
				}
				updated = append(updated, fmt.Sprintf("export %s=%q", item.key, item.value))
				replaced = true
				continue
			}
			updated = append(updated, line)
		}
		if !replaced {
			if len(updated) > 0 && updated[len(updated)-1] != "" {
				updated = append(updated, "")
			}
			updated = append(updated, fmt.Sprintf("export %s=%q", item.key, item.value))
		}
		if updated[len(updated)-1] != "" {
			updated = append(updated, "")
		}
		content = strings.Join(updated, "\n")
	}

	return content
}
