- name: Download Neovim AppImage
  become: yes
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    dest: /opt/nvim
    mode: '0755'
    force: yes

- name: Install lazyvim
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/LazyVim/starter
    dest: "{{ app_data_dir }}/nvim"
    force: yes

- name: Remove starter git data
  become: yes
  become_user: "{{ user }}"
  shell: >
    rm -rf ~/.config/nvim/.git

- name: Create vim symlink to nvim
  become: yes
  file:
    src: /opt/nvim
    dest: /usr/local/bin/vim
    state: link
    force: yes  # Overwrite existing vim if present
