- name: Install necessary packages
  apt:
    name:
      - zsh
      - tmux
      - fd-find
      - fzf
      - ripgrep
      - bat
      - trash-cli
      - zoxide
      - jq
    state: present

- name: Install eza via cargo
  become: yes
  become_user: "{{ user }}"
  shell: cargo install eza

- name: Check if antidote is already installed
  become: yes
  become_user: "{{ user }}"
  stat:
    path: "{{ app_data_dir }}/antidote"
  register: antidote_check

- name: Install antidote
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/mattmc3/antidote.git
    dest: "{{ app_data_dir }}/antidote"
    depth: 1
    clone: yes
    update: no
  when: not antidote_check.stat.exists

- name: Change default shell to zsh for specific user
  user:
    name: "{{ target_user }}"
    shell: /bin/zsh
  become: yes
  become_user: "{{ user }}"

- name: Copy shell config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ shell_cfgs }}"
  become: yes
  become_user: "{{ user }}"

- name: Install the powerlevel10k zsh theme.
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ app_data_dir }}/powerlevel10k"
    force: yes

- name: Configure tmux plugins and settings
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    force: yes

- name: install neovim 
  become: yes
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    dest: /opt/nvim
    mode: '0755'
    force: yes

- name: func_setup_lazyvim
  block:
    - name: func_lazyvim_install 
      block:

      - name: install lazyvim
        become: yes
        become_user: "{{ user }}"
        git:
          repo: https://github.com/LazyVim/starter
          dest: "{{ app_data_dir }}/nvim"
          force: yes

      - name: clean lazyvim
        become: yes
        become_user: "{{ user }}"
        shell: rm -rf ~/.config/nvim/.git

      - name: config symlink nvim
        become: yes
        file:
          src: /opt/nvim
          dest: /usr/local/bin/vim
          state: link
          force: yes
