- name: Install necessary packages
  apt:
    name:
      - zsh
      - tmux
    state: present

- name: Change default shell to zsh for specific user
  user:
    name: "{{ target_user }}"
    shell: /bin/zsh
  become: yes
