---
- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install necessary packages
  apt:
    name:
      - curl
      - tar
      - xz-utils
      - sudo
      - screen
      - locales
      - locales-all
      - fontconfig
      - fonts-dejavu-core
      - fonts-dejavu-extra
      - fonts-liberation
      - ttf-mscorefonts-installer
      - fonts-powerline
      - unzip
    state: present

- name: Install development dependencies
  apt:
    name:
      - git
      - npm
      - python3
    state: present


