- name: Install necessary packages
  apt:
    name:
      - fzf
      - ripgrep
      - bat
      - trash-cli
    state: present

- name: Install lazyvim
  become: yes
  become_user: "{{ user }}"
  shell: >
    git clone https://github.com/LazyVim/starter ~/.config/nvim && rm -rf ~/.config/nvim/.git
