---
- name: install(tool) dependencies
  apt:
    name:
      - ffmpeg
      - 7zip
      - poppler-utils
      - imagemagick
    state: present

- name: check(tools) if the TGUI file manager is already installed
  stat:
    path: "{{ user_home }}/.cargo/bin/yazi"
  register: yazi_installed

- name: func_setup_yazi
  block:
    - name: func_yazi_install 
      block:

      - name: install(tools) TGUI file manager
        become: yes
        become_user: "{{ user }}"
        shell: "{{ user_home }}/.cargo/bin/cargo install --locked yazi-fm yazi-cli"
        args:
          creates: "{{ user_home }}/.cargo/bin/yazi"

      when: not yazi_installed.stat.exists
          
    - name: func_ueberzugpp_install
      block:

      - name: install(tools) TGUI file manager image preview dependencies
        become: yes
        apt:
          deb: https://download.opensuse.org/repositories/home:/justkidding/xUbuntu_24.04/amd64/ueberzugpp_2.9.7_amd64.deb
          state: present
        ignore_errors: yes

    - name: install(tools) Update TGUI file manager 
      become: yes
      become_user: "{{ user }}"
      shell: "{{ user_home }}/.cargo/bin/rustup update"
      when: yazi_installed.stat.exists
      ignore_errors: yes

  when: not yazi_installed.stat.exists

- name: check(tools) if aider is already installed
  stat:
    path: "{{ user_home }}/.local/bin/aider"
  register: aider_installed

- name: func_setup_aider
  block:

    - name: install(tools) Aider 
      become: yes
      become_user: "{{ user }}"
      shell: curl -LsSf https://aider.chat/install.sh | sh
      args:
        creates: /usr/local/bin/aider

  when: not aider_installed.stat.exists

- name: Copy config files for aider, claude 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ tool_cfgs }}"
  become: yes
  become_user: "{{ user }}"
