package internal

import("encoding/json";"errors";"flag";"fmt";"io";"os";"path/filepath";"strings";"time";"planner/internal/workflow")
const workflowUsage=`usage:
  planner workflow id
  planner workflow start --id <id> --repo <repo> [--input <plan.md>] --output <plan.md> --operation <new|partial-update> [--skill <name>]...
  planner workflow show <id>
  planner workflow skill add <id> --expected-revision <N> --name <skill>
  planner workflow research bind <id> --expected-revision <N> --managed-root <root>
  planner workflow research complete <id> --expected-revision <N> --receipt <receipt.json>
  planner workflow evidence complete <id> --expected-revision <N> --review <manual-review.md> --disposition <evidence-disposition.md>
  planner workflow review complete <id> --expected-revision <N> --path <review.md> --outcome <pass|blocking>
  planner workflow fail <id> --expected-revision <N> --stage <stage> --reason <text>
  planner workflow finish <id> --expected-revision <N>`
type stringList []string
func(v *stringList)String()string{return strings.Join(*v,",")};func(v *stringList)Set(s string)error{*v=append(*v,s);return nil}
func runWorkflow(args []string,out,errout io.Writer)int{if len(args)==0||args[0]=="help"||args[0]=="--help"||args[0]=="-h"{fmt.Fprintln(out,workflowUsage);return 0};r,e:=dispatchWorkflow(args);if e!=nil{var ce *PlannerCLIError;if !errors.As(e,&ce){ce=newPlannerCLIError(PlannerRuntimeError,e,"workflow")};reportError(errout,"workflow",ce);return plannerExitCode(ce)};if e=json.NewEncoder(out).Encode(r);e!=nil{reportError(errout,"workflow",newPlannerCLIError(PlannerWriteOutputError,e,"workflow result"));return 1};return 0}
func dispatchWorkflow(a []string)(any,error){switch a[0]{case"id":if len(a)!=1{return nil,workflowUsageError(nil)};id,e:=workflow.NewID();return map[string]string{"workflow_id":id},e;case"start":return runWorkflowStart(a[1:]);case"show":return runWorkflowShow(a[1:]);case"fail":return runWorkflowFail(a[1:]);case"finish":return runWorkflowFinish(a[1:]);case"skill","research","evidence","review":if len(a)<2{return nil,workflowUsageError(nil)}};if a[0]=="skill"&&a[1]=="add"{return runWorkflowSkill(a[2:])};if a[0]=="research"&&a[1]=="bind"{return runWorkflowResearchBind(a[2:])};if a[0]=="research"&&a[1]=="complete"{return runWorkflowResearchComplete(a[2:])};if a[0]=="evidence"&&a[1]=="complete"{return runWorkflowEvidence(a[2:])};if a[0]=="review"&&a[1]=="complete"{return runWorkflowReview(a[2:])};return nil,workflowUsageError(nil)}
func wfFlags(n string)*flag.FlagSet{f:=flag.NewFlagSet(n,flag.ContinueOnError);f.SetOutput(io.Discard);return f}
func runWorkflowStart(a []string)(workflow.StartResult,error){f:=wfFlags("start");id:=f.String("id","","");repo:=f.String("repo","","");in:=f.String("input","","");out:=f.String("output","","");op:=f.String("operation","","");var skills stringList;f.Var(&skills,"skill","");e:=f.Parse(a);if e!=nil||f.NArg()!=0||*id==""||*repo==""||*out==""||(*op!="new"&&*op!="partial-update"){return workflow.StartResult{},workflowUsageError(e)};root,e:=workflowStateRoot();if e!=nil{return workflow.StartResult{},e};return workflow.Start(workflow.StartOptions{WorkflowID:*id,Repository:*repo,Input:*in,Output:*out,Operation:workflow.Operation(*op),Skills:skills,StateRoot:root,Now:time.Now})}
func runWorkflowShow(a []string)(workflow.State,error){if len(a)!=1{return workflow.State{},workflowUsageError(nil)};s,e:=openWorkflow(a[0]);if e!=nil{return workflow.State{},e};return s.Load()}
func updateFlags(a []string,n string)(string,*flag.FlagSet,*uint64,error){if len(a)==0{return"",nil,nil,workflowUsageError(nil)};f:=wfFlags(n);r:=f.Uint64("expected-revision",0,"");return a[0],f,r,nil}
func update(a []string,n string, action func(*workflow.Store,uint64)(workflow.State,error))(workflow.UpdateResult,error){id,f,r,e:=updateFlags(a,n);if e!=nil{return workflow.UpdateResult{},e};e=f.Parse(a[1:]);if e!=nil||f.NArg()!=0{return workflow.UpdateResult{},workflowUsageError(e)};if *r==0{return workflow.UpdateResult{},workflowUsageError(nil)};s,e:=openWorkflow(id);if e!=nil{return workflow.UpdateResult{},e};st,e:=action(s,*r);if e!=nil{return workflow.UpdateResult{},e};return workflow.UpdateResult{WorkflowID:st.WorkflowID,Revision:st.Revision,Stage:st.Stage,Completion:st.Completion},nil}
func runWorkflowSkill(a []string)(workflow.UpdateResult,error){f:=wfFlags("skill-add");name:=f.String("name","","");return updateWith(a,f,func(s *workflow.Store,r uint64)(workflow.State,error){if strings.TrimSpace(*name)==""{return workflow.State{},workflowUsageError(nil)};return workflow.AddSkill(s,r,*name)})}
func updateWith(a []string,f *flag.FlagSet,action func(*workflow.Store,uint64)(workflow.State,error))(workflow.UpdateResult,error){if len(a)==0{return workflow.UpdateResult{},workflowUsageError(nil)};id:=a[0];r:=f.Uint64("expected-revision",0,"");if e:=f.Parse(a[1:]);e!=nil||f.NArg()!=0{return workflow.UpdateResult{},workflowUsageError(nil)};if *r==0{return workflow.UpdateResult{},workflowUsageError(nil)};s,e:=openWorkflow(id);if e!=nil{return workflow.UpdateResult{},e};st,e:=action(s,*r);if e!=nil{return workflow.UpdateResult{},e};return workflow.UpdateResult{WorkflowID:st.WorkflowID,Revision:st.Revision,Stage:st.Stage,Completion:st.Completion},nil}
func runWorkflowResearchBind(a []string)(workflow.UpdateResult,error){f:=wfFlags("research-bind");root:=f.String("managed-root","","");return updateWith(a,f,func(s *workflow.Store,r uint64)(workflow.State,error){if *root==""{return workflow.State{},workflowUsageError(nil)};return workflow.BindResearch(s,r,*root)})}
func runWorkflowResearchComplete(a []string)(workflow.UpdateResult,error){f:=wfFlags("research-complete");p:=f.String("receipt","","");return updateWith(a,f,func(s *workflow.Store,r uint64)(workflow.State,error){if *p==""{return workflow.State{},workflowUsageError(nil)};return workflow.CompleteResearch(s,r,*p)})}
func runWorkflowEvidence(a []string)(workflow.UpdateResult,error){f:=wfFlags("evidence-complete");r:=f.String("review","","");d:=f.String("disposition","","");return updateWith(a,f,func(s *workflow.Store,n uint64)(workflow.State,error){if *r==""||*d==""{return workflow.State{},workflowUsageError(nil)};return workflow.CompleteEvidence(s,n,*r,*d)})}
func runWorkflowReview(a []string)(workflow.UpdateResult,error){f:=wfFlags("review-complete");p:=f.String("path","","");o:=f.String("outcome","","");return updateWith(a,f,func(s *workflow.Store,r uint64)(workflow.State,error){if *p==""||(*o!="pass"&&*o!="blocking"){return workflow.State{},workflowUsageError(nil)};return workflow.RecordReview(s,r,*p,*o)})}
func runWorkflowFail(a []string)(workflow.UpdateResult,error){f:=wfFlags("fail");stage:=f.String("stage","","");reason:=f.String("reason","","");return updateWith(a,f,func(s *workflow.Store,r uint64)(workflow.State,error){valid:=map[string]bool{"research":true,"evidence":true,"authoring":true,"review":true,"finalization":true};if !valid[*stage]||strings.TrimSpace(*reason)==""{return workflow.State{},workflowUsageError(nil)};return workflow.Fail(s,r,*stage,*reason)})}
func runWorkflowFinish(a []string)(workflow.UpdateResult,error){return update(a,"finish",func(s *workflow.Store,r uint64)(workflow.State,error){return workflow.Finish(s,r,validatePlanBytes)})}
func openWorkflow(id string)(*workflow.Store,error){r,e:=workflowStateRoot();if e!=nil{return nil,e};return workflow.Open(r,id,time.Now)}
func workflowStateRoot()(string,error){if v:=os.Getenv("XDG_STATE_HOME");filepath.IsAbs(v){return filepath.Join(v,"planner","workflows"),nil};h:=os.Getenv("HOME");if !filepath.IsAbs(h){return"",errors.New("HOME must be an absolute path")};return filepath.Join(h,".local","state","planner","workflows"),nil}
func workflowUsageError(e error)*PlannerCLIError{return newPlannerCLIError(PlannerUsageError,e,workflowUsage)}
func validatePlanBytes(raw []byte)error{p,e:=ParseMarkdown(string(raw));if e!=nil{return plannerMarkdownDecodeError(raw,e)};if fs:=ValidatePlanAll(p.Plan);len(fs)>0{m:=make([]string,len(fs));for i,f:=range fs{m[i]=f.Message};return newPlannerCLIError(PlannerValidateInputError,errors.New(strings.Join(m,"\n")),"plan")};return nil}
