---
- name: Setup Development Environment
  hosts: local
  become: yes
  vars:
    user: "{{ user }}"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - curl
          - tar
          - xz-utils
          - sudo
          - screen
          - locales
          - locales-all
          - fontconfig
          - fonts-dejavu-core
          - fonts-dejavu-extra
          - fonts-liberation
          - ttf-mscorefonts-installer
          - fonts-powerline
          - zsh
          - git
          - neovim
          - tmux
          - npm
          - stow
          - python3
          - fzf
          - ripgrep
          - bat
        state: present

    - name: Set locale
      locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Add user
      user:
        name: "{{ user }}"
        shell: /bin/bash
        create_home: yes

    - name: Add user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"

    - name: Create fonts directory
      file:
        path: "/home/{{ user }}/.local/share/fonts"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
      become: yes

    - name: Check if JetBrainsMono Nerd Font is already installed
      stat:
        path: "/home/{{ user }}/.local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf"
      register: jetbrains_font_exists

    - name: Download and install all Nerd Fonts
      block:
        - name: Download UbuntuMono Nerd Font
          get_url:
            url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/UbuntuMono.zip
            dest: /tmp/UbuntuMono.tar.xz

        - name: Ensure destination directory exists
          file:
            path: "/home/{{ user }}/.fonts"
            state: directory
            owner: "{{ user }}"
            group: "{{ user }}"
            recurse: yes

        - name: Extract UbuntuMono Nerd Font
          unarchive:
            src: /tmp/UbuntuMono.tar.xz
            dest: "/home/{{ user }}/.fonts"
            owner: "{{ user }}"
            group: "{{ user }}"
            remote_src: yes

        - name: Download JetBrainsMono Nerd Font
          get_url:
            url: https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.tar.xz
            dest: /tmp/JetBrainsMono.tar.xz
          
        - name: Extract JetBrainsMono Nerd Font
          unarchive:
            src: /tmp/JetBrainsMono.tar.xz
            dest: "/home/{{ user }}/.local/share/fonts"
            owner: "{{ user }}"
            group: "{{ user }}"
            remote_src: yes
        
        - name: Refresh font cache
          command: fc-cache -fv
          become: yes
          become_user: "{{ user }}"
        
        - name: Clean up downloaded archive
          file:
            path: /tmp/UbuntuMono.tar.xz
            state: absent

        - name: Clean up downloaded archive
          file:
            path: /tmp/JetBrainsMono.tar.xz
            state: absent
    
      when: not jetbrains_font_exists.stat.exists
      become: yes

    - name: Change default shell to zsh
      user:
        name: "{{ user }}"
        shell: /bin/zsh

    - name: Add zsh to valid login shells
      lineinfile:
        path: /etc/shells
        state: present
        line: /bin/zsh

    - name: Copy configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default(omit) }}"
      with_items:
        - { src: 'config/zsh/.zsh_plugins.txt', dest: '/home/{{ user }}/.zsh_plugins.txt' }
        - { src: 'config/zsh/.zshrc', dest: '/home/{{ user }}/.zshrc' }
        - { src: 'config/tmux/.tmux.conf', dest: '/home/{{ user }}/.tmux.conf' }
        - { src: 'config', dest: '/home/{{ user }}/config', mode: '0755' }
        - { src: 'config/screen/.screenrc', dest: '/home/{{ user }}/.screenrc' }
      become: yes
      become_user: "{{ user }}"

    - name: Change ownership of home directory files
      file:
        path: "/home/{{ user }}/{{ item }}"
        owner: "{{ user }}"
      with_items:
        - .zsh_plugins.txt
        - .zshrc
        - .tmux.conf
        - .config
        - .screenrc

    - name: Install antibody
      become: yes
      shell: >
        curl -sfL git.io/antibody | sh -s - -b /usr/local/bin

    - name: Bundle zsh plugins with antibody
      become: yes
      become_user: "{{ user }}"
      shell: antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh

    - name: Download and install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm"

    - name: Install Node.js using nvm
      shell: >
        source {{ ansible_env.HOME }}/.nvm/nvm.sh &&
        nvm install {{ node_version | default('18') }} &&
        nvm use {{ node_version | default('18') }}
      args:
        executable: /bin/bash

    - name: Install lazyvim
      become: yes
      become_user: "{{ user }}"
      shell: >
        git clone https://github.com/LazyVim/starter ~/.config/nvim && rm -rf ~/.config/nvim/.git

    - name: Configure tmux plugins and settings
      become: yes
      become_user: "{{ user }}"
      shell: >
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

    - name: Install the powerlevel10k zsh theme. 
      become: yes
      become_user: "{{ user }}"
      shell: >
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/powerlevel10k


