# Change prefix from 'Ctrl+B' to 'Ctrl+A'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Accidentally pressing space closes windows and I don't like that.
unbind Space

set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# tmux resurrect config
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-processes 'ssh vim nvim'
set -g @resurrect-capture-pane-contents 'on'

# Make copy pasting easier by enabling vim keybindings for scroll mode.
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
# These commands only work on Linux and ally copy pasting in scroll mode.
set -s copy-command 'xclip -in -selection clipboard'
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
# Enable mouse activation of scroll mode.
set -g mouse on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

