mod chunk;
mod gather;
mod index;
mod merge;
mod research;
mod schema;
mod session;
mod source;
mod taskfile;

use clap::{ArgGroup, Args, Parser, Subcommand};
use std::convert::TryFrom;
use std::error::Error;
use std::io::{self, Write};
use std::path::PathBuf;

#[derive(Parser)]
#[command(
    name = "surveil",
    version,
    about = "Research repositories with structured tasks and evidence"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Build one task context from repository files.
    Gather(GatherArgs),
    /// Create task documents and managed research roots.
    New(NewArgs),
    /// Build the optional repository search index.
    Index(IndexArgs),
    /// Combine task reports into one evidence pack.
    Merge(MergeArgs),
    /// Research one gathered task context.
    Research(ResearchArgs),
    /// Run all tasks in an existing managed root.
    Session(SessionArgs),
}

#[derive(Args)]
struct SessionArgs {
    #[command(subcommand)]
    command: SessionCommand,
}

#[derive(Subcommand)]
enum SessionCommand {
    #[command(
        about = "Run every populated task in a managed root",
        long_about = "Run every populated task in one existing Surveil-managed root.\n\nTasks are discovered only from immediate child directories and processed sequentially in sorted task-name order. Each task is gathered and researched, then all reports are merged. At its own research startup, each task independently uses a usable repository index or performs the existing lexical scan; this command does not create or rebuild an index.\n\nAll files are staged below the managed root. The completed .surveil-session directory becomes visible only after every task, merge, artifact digest, and receipt succeeds.",
        after_help = "Artifacts:\n  <MANAGED_ROOT>/.surveil-session/tasks/<TASK>/context.json\n  <MANAGED_ROOT>/.surveil-session/tasks/<TASK>/trace.json\n  <MANAGED_ROOT>/.surveil-session/tasks/<TASK>/report.json\n  <MANAGED_ROOT>/.surveil-session/evidence.json\n  <MANAGED_ROOT>/.surveil-session/receipt.json\n\nBehavior:\n  Tasks run sequentially in sorted name order.\n  Completed output is atomically published after all work succeeds.\n  Failures before publication create no .surveil-session path.\n  An existing .surveil-session path refuses rerun.\n\nExample:\n  surveil session run --repo /path/to/repo --root /path/to/managed-root"
    )]
    Run(SessionRunArgs),
}

#[derive(Args)]
struct SessionRunArgs {
    /// Repository root researched by every task.
    #[arg(long, value_name = "REPO")]
    repo: PathBuf,

    /// Existing UTF-8 absolute root created by `surveil new task --task`.
    #[arg(long, value_name = "MANAGED_ROOT")]
    root: PathBuf,
}

#[derive(Args)]
struct GatherArgs {
    /// Repository root. Relative explicit_files and search_areas values resolve against this path; use `.` for the root itself.
    #[arg(long, value_name = "REPO")]
    repo: PathBuf,

    /// JSON task file generated by `surveil new task`.
    #[arg(long = "task-file", value_name = "TASK_JSON")]
    task_file: PathBuf,
}

#[derive(Args)]
struct NewArgs {
    #[command(subcommand)]
    command: NewCommand,
}

#[derive(Subcommand)]
enum NewCommand {
    /// Create a task document in an explicit or managed directory.
    Task(NewTaskArgs),
}

#[derive(Args)]
#[command(group(
    ArgGroup::new("task_destination")
        .required(true)
        .multiple(false)
        .args(["output_dir", "task"])
))]
struct NewTaskArgs {
    /// Directory where task.json is created.
    output_dir: Option<PathBuf>,

    /// Managed task name to create.
    #[arg(long, conflicts_with = "output_dir")]
    task: Option<String>,

    /// Existing absolute managed root receiving the task.
    #[arg(long, requires = "task", conflicts_with = "output_dir")]
    root: Option<PathBuf>,
}

#[derive(Debug, PartialEq, Eq)]
enum NewTaskMode {
    Explicit { output_dir: PathBuf },
    ManagedNew { task: String },
    ManagedAppend { root: PathBuf, task: String },
}

impl TryFrom<NewTaskArgs> for NewTaskMode {
    type Error = io::Error;

    fn try_from(args: NewTaskArgs) -> Result<Self, Self::Error> {
        match (args.output_dir, args.root, args.task) {
            (Some(output_dir), None, None) => Ok(Self::Explicit { output_dir }),
            (None, None, Some(task)) => Ok(Self::ManagedNew { task }),
            (None, Some(root), Some(task)) => Ok(Self::ManagedAppend { root, task }),
            _ => Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                "use <output-dir>, --task <name>, or --root <root> --task <name>",
            )),
        }
    }
}

#[derive(Args)]
struct IndexArgs {
    /// Repository root to index.
    #[arg(long, value_name = "REPO")]
    repo: PathBuf,
}

#[derive(Args)]
struct MergeArgs {
    /// Task report JSON files to merge in argument order.
    #[arg(required = true, num_args = 1.., value_name = "TASK_REPORT")]
    reports: Vec<PathBuf>,
}

#[derive(Args)]
struct ResearchArgs {
    /// Gathered task context JSON.
    #[arg(long, value_name = "CONTEXT_JSON")]
    context: PathBuf,

    /// Destination for the research trace JSON.
    #[arg(long = "trace-out", value_name = "TRACE_JSON")]
    trace_out: PathBuf,
}

fn main() {
    if let Err(err) = run() {
        eprintln!("{err}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), Box<dyn Error>> {
    let cli = Cli::parse();

    match cli.command {
        Command::Gather(args) => gather::run(&args.repo, &args.task_file),
        Command::New(args) => match args.command {
            NewCommand::Task(args) => match NewTaskMode::try_from(args)? {
                NewTaskMode::Explicit { output_dir } => {
                    taskfile::run(&output_dir).map_err(Into::into)
                }
                NewTaskMode::ManagedNew { task } => {
                    let root = taskfile::create_managed_task(&taskfile::state_root()?, &task)?;
                    println!("{}", root.display());
                    Ok(())
                }
                NewTaskMode::ManagedAppend { root, task } => {
                    taskfile::append_managed_task(&root, &task)?;
                    println!("{}", root.display());
                    Ok(())
                }
            },
        },
        Command::Index(args) => index::build_chunk_index(&args.repo),
        Command::Merge(args) => merge::run(&args.reports),
        Command::Research(args) => research::run(&args.context, &args.trace_out),
        Command::Session(args) => match args.command {
            SessionCommand::Run(args) => {
                let receipt = session::run(&args.repo, &args.root)?;
                let receipt = receipt.to_str().ok_or_else(|| {
                    io::Error::new(io::ErrorKind::InvalidData, "receipt path must be UTF-8")
                })?;
                let stdout = io::stdout();
                let mut output = stdout.lock();
                writeln!(output, "{receipt}")?;
                output.flush()?;
                Ok(())
            }
        },
    }
}

#[cfg(test)]
mod tests {
    use super::{Cli, Command, NewCommand, NewTaskMode, SessionCommand};
    use clap::error::ErrorKind;
    use clap::Parser;
    use std::convert::TryFrom;
    use std::path::PathBuf;

    #[test]
    fn parses_new_task_modes() {
        let cases = [
            (
                vec!["surveil", "new", "task", "/tmp/tasks"],
                Some(NewTaskMode::Explicit {
                    output_dir: PathBuf::from("/tmp/tasks"),
                }),
                None,
            ),
            (
                vec!["surveil", "new", "task", "--task", "architecture"],
                Some(NewTaskMode::ManagedNew {
                    task: "architecture".to_string(),
                }),
                None,
            ),
            (
                vec![
                    "surveil",
                    "new",
                    "task",
                    "--root",
                    "/state/run",
                    "--task",
                    "tests",
                ],
                Some(NewTaskMode::ManagedAppend {
                    root: PathBuf::from("/state/run"),
                    task: "tests".to_string(),
                }),
                None,
            ),
            (
                vec!["surveil", "new", "task"],
                None,
                Some(ErrorKind::MissingRequiredArgument),
            ),
            (
                vec![
                    "surveil",
                    "new",
                    "task",
                    "/tmp/tasks",
                    "--task",
                    "architecture",
                ],
                None,
                Some(ErrorKind::ArgumentConflict),
            ),
        ];

        for (args, expected, error) in cases {
            match Cli::try_parse_from(args) {
                Ok(Cli {
                    command: Command::New(args),
                }) => match args.command {
                    NewCommand::Task(args) => assert_eq!(
                        NewTaskMode::try_from(args).expect("task mode"),
                        expected.expect("expected mode"),
                    ),
                },
                Ok(_) => panic!("expected new task command"),
                Err(err) => assert_eq!(err.kind(), error.expect("expected error")),
            }
        }
    }

    #[test]
    fn parses_merge_reports() {
        let cli = Cli::try_parse_from([
            "surveil",
            "merge",
            "/tmp/architecture.json",
            "/tmp/tests.json",
        ])
        .expect("parse merge command");

        match cli.command {
            Command::Merge(args) => assert_eq!(
                args.reports,
                vec![
                    PathBuf::from("/tmp/architecture.json"),
                    PathBuf::from("/tmp/tests.json"),
                ]
            ),
            _ => panic!("expected merge command"),
        }
    }

    #[test]
    fn merge_requires_report() {
        match Cli::try_parse_from(["surveil", "merge"]) {
            Ok(_) => panic!("expected missing argument error"),
            Err(err) => assert_eq!(err.kind(), ErrorKind::MissingRequiredArgument),
        }
    }

    #[test]
    fn parses_session_run() {
        let cli = Cli::try_parse_from([
            "surveil",
            "session",
            "run",
            "--repo",
            "/repo",
            "--root",
            "/state/run",
        ])
        .expect("parse session run");

        match cli.command {
            Command::Session(args) => match args.command {
                SessionCommand::Run(args) => {
                    assert_eq!(args.repo, PathBuf::from("/repo"));
                    assert_eq!(args.root, PathBuf::from("/state/run"));
                }
            },
            _ => panic!("expected session command"),
        }
    }
}
