version: "2"
run:
  timeout: 3m
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errorlint
    - misspell
    - revive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
