name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  planner:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: planner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: planner/go.mod
          cache-dependency-path: planner/go.sum
      - name: install golangci-lint
        run: make init
      - name: check
        run: make check

  cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: cli/go.mod
          cache-dependency-path: cli/go.sum
      - name: test
        run: go test ./...

  surveil:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --release --manifest-path surveil/Cargo.toml
      - name: test
        run: cargo test --manifest-path surveil/Cargo.toml
